// src/lib/presets.ts
import { ButtonConfig } from '@/types/button';

export interface ButtonPreset {
  id: string;
  name: string;
  icon: string;
  config: ButtonConfig;
}

// Базовый конфиг для пресетов
const basePresetConfig: ButtonConfig = {
  text: 'Button',
  bgColor: '#3b82f6',
  textColor: '#ffffff',
  borderRadius: 8,
  borderWidth: 0,
  borderColor: '#000000',
  size: 'md',
  customPaddingX: 32,
  customPaddingY: 12,
  customFontSize: 16,
  width: 'auto',
  customWidth: 200,
  icon: null,
  iconPosition: 'left',
  iconSize: 20,
  enableGradient: false,
  gradientType: 'linear',
  gradientAngle: 135,
  gradientColor1: '#3b82f6',
  gradientColor2: '#8b5cf6',
  gradientColor3: '',
  gradientText: false,
  enableShadow: true,
  shadowX: 0,
  shadowY: 10,
  shadowBlur: 25,
  shadowSpread: -5,
  shadowColor: '#000000',
  shadowOpacity: 20,
  insetShadow: false,
  secondShadow: false,
  secondShadowX: 0,
  secondShadowY: 10,
  secondShadowBlur: 20,
  secondShadowColor: '#000000',
  secondShadowOpacity: 15,
  enableGlow: false,
  glowColor: '#3b82f6',
  glowBlur: 20,
  glowOpacity: 50,
  animatedBorder: false,
  borderColor1: '#3b82f6',
  borderColor2: '#8b5cf6',
  borderAnimationSpeed: 3,
  
  // === ДОБАВЛЕННЫЕ ПОЛЯ ДЛЯ ГРАДИЕНТНОЙ ГРАНИЦЫ ===
  gradientBorder: false,
  gradientBorderAngle: 45,
  gradientBorderColor1: '#3b82f6',
  gradientBorderColor2: '#8b5cf6',
  gradientBorderColor3: '#ec4899',
  // ==================================================

  ripple: false,
  rippleColor: 'rgba(255, 255, 255, 0.6)',
  tilt3D: false,
  tiltIntensity: 10,
  magnetic: false,
  magneticStrength: 50,
  hoverAnimation: 'none',
  entranceAnimation: 'none',
  hoverBgColor: '',
  hoverTextColor: '',
  enableHoverTransition: true,
  transitionDuration: 0.3,
  loading: false,
  disabled: false,
  whileHoverScale: 1.05,
  whileTapScale: 0.95,
  customClasses: '',
};

export const buttonPresets: ButtonPreset[] = [
  {
    id: 'primary',
    name: 'Classic',
    icon: 'Sparkles',
    config: {
      ...basePresetConfig,
      text: 'Get Started',
      bgColor: '#3b82f6',
      hoverAnimation: 'scale',
    },
  },
  {
    id: 'gradient',
    name: 'Gradient',
    icon: 'Palette',
    config: {
      ...basePresetConfig,
      text: 'Explore Now',
      bgColor: '#ec4899',
      borderRadius: 9999,
      enableGradient: true,
      gradientColor1: '#8b5cf6',
      gradientColor2: '#ec4899',
      gradientColor3: '#f43f5e',
      shadowColor: '#8b5cf6',
      shadowOpacity: 40,
    },
  },
  {
    id: 'outline',
    name: 'Outline',
    icon: 'Square',
    config: {
      ...basePresetConfig,
      text: 'Learn More',
      bgColor: '#ffffff',
      textColor: '#1f2937',
      borderWidth: 2,
      borderColor: '#1f2937',
      enableShadow: false,
      hoverAnimation: 'bounce',
    },
  },
  {
    id: '3d',
    name: '3D Push',
    icon: 'Box',
    config: {
      ...basePresetConfig,
      text: 'Press Me',
      bgColor: '#f59e0b',
      borderRadius: 12,
      shadowY: 6,
      shadowBlur: 0,
      shadowColor: '#b45309',
      shadowOpacity: 100,
      whileHoverScale: 1,
      whileTapScale: 1,
      tilt3D: true,
      tiltIntensity: 15,
    },
  },
  {
    id: 'ghost',
    name: 'Ghost',
    icon: 'Ghost',
    config: {
      ...basePresetConfig,
      text: 'Cancel',
      bgColor: 'transparent',
      textColor: '#6b7280',
      borderRadius: 6,
      enableShadow: false,
      enableHoverTransition: true,
      hoverBgColor: '#f3f4f6',
      ripple: true,
    },
  },
];